// flow-typed signature: 01adca3825dfb46b47b323d7f90e9f71
// flow-typed version: <<STUB>>/babel-template_v^6.24.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-template' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-template/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-template/lib/index.js' {
  declare module.exports: $Exports<'babel-template/lib/index'>;
}
