// flow-typed signature: a6ad91380c18f47f547e7a7c5a861bfd
// flow-typed version: <<STUB>>/fs-jetpack_v^0.13.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-jetpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-jetpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs-jetpack/benchmark/copy' {
  declare module.exports: any;
}

declare module 'fs-jetpack/benchmark/remove' {
  declare module.exports: any;
}

declare module 'fs-jetpack/benchmark/utils' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/append' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/copy' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/dir' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/exists' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/file' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/find' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/inspect_tree' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/inspect' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/jetpack' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/list' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/move' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/read' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/remove' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/rename' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/streams' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/symlink' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/fs' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/matcher' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/mode' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/promisify' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/tree_walker' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/utils/validate' {
  declare module.exports: any;
}

declare module 'fs-jetpack/lib/write' {
  declare module.exports: any;
}

declare module 'fs-jetpack/main' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/append.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/assert_path' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/copy.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/cwd.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/dir.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/exists.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/file.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/find.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/helper' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/inspect_tree.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/inspect.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/list.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/log.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/move.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/path.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/read.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/remove.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/rename.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/streams.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/symlink.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/utils/fs.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/utils/matcher.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/utils/tree_walker.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/utils/validate.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/write_atomic.spec' {
  declare module.exports: any;
}

declare module 'fs-jetpack/spec/write.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs-jetpack/benchmark/copy.js' {
  declare module.exports: $Exports<'fs-jetpack/benchmark/copy'>;
}
declare module 'fs-jetpack/benchmark/remove.js' {
  declare module.exports: $Exports<'fs-jetpack/benchmark/remove'>;
}
declare module 'fs-jetpack/benchmark/utils.js' {
  declare module.exports: $Exports<'fs-jetpack/benchmark/utils'>;
}
declare module 'fs-jetpack/lib/append.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/append'>;
}
declare module 'fs-jetpack/lib/copy.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/copy'>;
}
declare module 'fs-jetpack/lib/dir.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/dir'>;
}
declare module 'fs-jetpack/lib/exists.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/exists'>;
}
declare module 'fs-jetpack/lib/file.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/file'>;
}
declare module 'fs-jetpack/lib/find.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/find'>;
}
declare module 'fs-jetpack/lib/inspect_tree.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/inspect_tree'>;
}
declare module 'fs-jetpack/lib/inspect.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/inspect'>;
}
declare module 'fs-jetpack/lib/jetpack.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/jetpack'>;
}
declare module 'fs-jetpack/lib/list.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/list'>;
}
declare module 'fs-jetpack/lib/move.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/move'>;
}
declare module 'fs-jetpack/lib/read.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/read'>;
}
declare module 'fs-jetpack/lib/remove.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/remove'>;
}
declare module 'fs-jetpack/lib/rename.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/rename'>;
}
declare module 'fs-jetpack/lib/streams.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/streams'>;
}
declare module 'fs-jetpack/lib/symlink.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/symlink'>;
}
declare module 'fs-jetpack/lib/utils/fs.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/fs'>;
}
declare module 'fs-jetpack/lib/utils/matcher.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/matcher'>;
}
declare module 'fs-jetpack/lib/utils/mode.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/mode'>;
}
declare module 'fs-jetpack/lib/utils/promisify.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/promisify'>;
}
declare module 'fs-jetpack/lib/utils/tree_walker.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/tree_walker'>;
}
declare module 'fs-jetpack/lib/utils/validate.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/utils/validate'>;
}
declare module 'fs-jetpack/lib/write.js' {
  declare module.exports: $Exports<'fs-jetpack/lib/write'>;
}
declare module 'fs-jetpack/main.js' {
  declare module.exports: $Exports<'fs-jetpack/main'>;
}
declare module 'fs-jetpack/spec/append.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/append.spec'>;
}
declare module 'fs-jetpack/spec/assert_path.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/assert_path'>;
}
declare module 'fs-jetpack/spec/copy.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/copy.spec'>;
}
declare module 'fs-jetpack/spec/cwd.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/cwd.spec'>;
}
declare module 'fs-jetpack/spec/dir.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/dir.spec'>;
}
declare module 'fs-jetpack/spec/exists.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/exists.spec'>;
}
declare module 'fs-jetpack/spec/file.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/file.spec'>;
}
declare module 'fs-jetpack/spec/find.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/find.spec'>;
}
declare module 'fs-jetpack/spec/helper.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/helper'>;
}
declare module 'fs-jetpack/spec/inspect_tree.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/inspect_tree.spec'>;
}
declare module 'fs-jetpack/spec/inspect.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/inspect.spec'>;
}
declare module 'fs-jetpack/spec/list.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/list.spec'>;
}
declare module 'fs-jetpack/spec/log.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/log.spec'>;
}
declare module 'fs-jetpack/spec/move.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/move.spec'>;
}
declare module 'fs-jetpack/spec/path.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/path.spec'>;
}
declare module 'fs-jetpack/spec/read.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/read.spec'>;
}
declare module 'fs-jetpack/spec/remove.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/remove.spec'>;
}
declare module 'fs-jetpack/spec/rename.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/rename.spec'>;
}
declare module 'fs-jetpack/spec/streams.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/streams.spec'>;
}
declare module 'fs-jetpack/spec/symlink.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/symlink.spec'>;
}
declare module 'fs-jetpack/spec/utils/fs.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/utils/fs.spec'>;
}
declare module 'fs-jetpack/spec/utils/matcher.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/utils/matcher.spec'>;
}
declare module 'fs-jetpack/spec/utils/tree_walker.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/utils/tree_walker.spec'>;
}
declare module 'fs-jetpack/spec/utils/validate.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/utils/validate.spec'>;
}
declare module 'fs-jetpack/spec/write_atomic.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/write_atomic.spec'>;
}
declare module 'fs-jetpack/spec/write.spec.js' {
  declare module.exports: $Exports<'fs-jetpack/spec/write.spec'>;
}
