// flow-typed signature: 3e2b2f32e16bf4abaf159dc68ecd61c3
// flow-typed version: <<STUB>>/svgicons2svgfont_v^5.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svgicons2svgfont'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svgicons2svgfont' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svgicons2svgfont/bin/svgicons2svgfont' {
  declare module.exports: any;
}

declare module 'svgicons2svgfont/src/filesorter' {
  declare module.exports: any;
}

declare module 'svgicons2svgfont/src/iconsdir' {
  declare module.exports: any;
}

declare module 'svgicons2svgfont/src/index' {
  declare module.exports: any;
}

declare module 'svgicons2svgfont/src/metadata' {
  declare module.exports: any;
}

declare module 'svgicons2svgfont/src/svgshapes2svgpath' {
  declare module.exports: any;
}

declare module 'svgicons2svgfont/tests/cli.mocha' {
  declare module.exports: any;
}

declare module 'svgicons2svgfont/tests/filesorter.mocha' {
  declare module.exports: any;
}

declare module 'svgicons2svgfont/tests/index.mocha' {
  declare module.exports: any;
}

declare module 'svgicons2svgfont/tests/metadata.mocha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svgicons2svgfont/bin/svgicons2svgfont.js' {
  declare module.exports: $Exports<'svgicons2svgfont/bin/svgicons2svgfont'>;
}
declare module 'svgicons2svgfont/src/filesorter.js' {
  declare module.exports: $Exports<'svgicons2svgfont/src/filesorter'>;
}
declare module 'svgicons2svgfont/src/iconsdir.js' {
  declare module.exports: $Exports<'svgicons2svgfont/src/iconsdir'>;
}
declare module 'svgicons2svgfont/src/index.js' {
  declare module.exports: $Exports<'svgicons2svgfont/src/index'>;
}
declare module 'svgicons2svgfont/src/metadata.js' {
  declare module.exports: $Exports<'svgicons2svgfont/src/metadata'>;
}
declare module 'svgicons2svgfont/src/svgshapes2svgpath.js' {
  declare module.exports: $Exports<'svgicons2svgfont/src/svgshapes2svgpath'>;
}
declare module 'svgicons2svgfont/tests/cli.mocha.js' {
  declare module.exports: $Exports<'svgicons2svgfont/tests/cli.mocha'>;
}
declare module 'svgicons2svgfont/tests/filesorter.mocha.js' {
  declare module.exports: $Exports<'svgicons2svgfont/tests/filesorter.mocha'>;
}
declare module 'svgicons2svgfont/tests/index.mocha.js' {
  declare module.exports: $Exports<'svgicons2svgfont/tests/index.mocha'>;
}
declare module 'svgicons2svgfont/tests/metadata.mocha.js' {
  declare module.exports: $Exports<'svgicons2svgfont/tests/metadata.mocha'>;
}
